"""
Build Smith County, TX realtor contact CSV from scraped data.
"""

import csv, os

OUTPUT = "output/smith_county_realtors.csv"
FIELDS = ["name", "phone", "email", "office", "brokerage", "address", "city", "state", "zip", "profile_url", "source", "notes"]

contacts = [
    # ── GTAR / General directory ──────────────────────────────────────────────
    {
        "name": "GTAR Main Office",
        "phone": "(903) 561-8403",
        "email": "",
        "office": "Greater Tyler Association of REALTORS®",
        "brokerage": "GTAR",
        "address": "2772 SSE Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.gtar.com/active-agents/",
        "source": "GTAR",
        "notes": "Association office — full active agent roster at profile_url",
    },

    # ── Coldwell Banker Apex — Tyler ──────────────────────────────────────────
    {
        "name": "Coldwell Banker Apex Tyler Office",
        "phone": "(903) 581-2584",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.cbapex.com/office/cbapr21/-525-wsw-loop-323-tyler-tx-75701",
        "source": "cbapex.com",
        "notes": "Main office line",
    },
    {
        "name": "Bobbie Harris",
        "phone": "(903) 530-6316",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "HAR.com / cbapex.com",
        "notes": "",
    },
    {
        "name": "Barbara Phaup",
        "phone": "(903) 581-2584",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "HAR.com / cbapex.com",
        "notes": "",
    },
    {
        "name": "Beth Edwards",
        "phone": "(903) 571-2949",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "HAR.com / cbapex.com",
        "notes": "",
    },
    {
        "name": "Kara Vinson",
        "phone": "(903) 581-2584",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "HAR.com / cbapex.com",
        "notes": "",
    },
    {
        "name": "Jan Chamnes",
        "phone": "(903) 571-0726",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "HAR.com / cbapex.com",
        "notes": "",
    },
    {
        "name": "Angela Shires",
        "phone": "(903) 714-2365",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "HAR.com / cbapex.com",
        "notes": "",
    },
    {
        "name": "Ginger Chandler",
        "phone": "(903) 581-2584",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "HAR.com / cbapex.com",
        "notes": "",
    },
    {
        "name": "Steven Clark",
        "phone": "(903) 581-2584",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "HAR.com / cbapex.com",
        "notes": "",
    },
    {
        "name": "Pamela Foughty",
        "phone": "(903) 581-2584",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "HAR.com / cbapex.com",
        "notes": "",
    },
    {
        "name": "Tristan Mosher",
        "phone": "(903) 283-0509",
        "email": "",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.cbapex.com/agent/9032830509/tristan-x-mosher",
        "source": "cbapex.com",
        "notes": "East Texas native",
    },
    {
        "name": "Julie Davis",
        "phone": "(903) 570-8704",
        "email": "realtorjuliedavis@yahoo.com",
        "office": "Coldwell Banker Apex",
        "brokerage": "Coldwell Banker Apex",
        "address": "525 WSW Loop 323",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/coldwell-banker-apex---tyler/broker_GTARTX-93",
        "source": "GTAR search",
        "notes": "",
    },

    # ── RE/MAX Tyler ──────────────────────────────────────────────────────────
    {
        "name": "RE/MAX Tyler Office",
        "phone": "(903) 581-7117",
        "email": "",
        "office": "RE/MAX Tyler",
        "brokerage": "RE/MAX",
        "address": "4300 Kinsey Dr",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.remax.com/real-estate-offices/remax-tyler-tyler-tx/100424348",
        "source": "remax.com",
        "notes": "60+ agents; 5 locations",
    },
    {
        "name": "Mary Smith",
        "phone": "(903) 530-9707",
        "email": "",
        "office": "RE/MAX Tyler",
        "brokerage": "RE/MAX",
        "address": "4300 Kinsey Dr",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.remax.com/real-estate-agents/mary-smith-tyler-tx/100034906",
        "source": "remax.com",
        "notes": "Broker-Associate; 32 yrs experience; License #436913; ABR CDPE EPRO GREEN RSPS SRES",
    },
    {
        "name": "Rebecca Burks",
        "phone": "(903) 521-9049",
        "email": "",
        "office": "RE/MAX Professionals",
        "brokerage": "RE/MAX",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://www.remax.com/real-estate-agents/rebecca-burks-tyler-tx/100035612",
        "source": "remax.com",
        "notes": "Team Leader; 46 yrs experience; License #0271366; ABR CRS; office: (903) 561-2600",
    },
    {
        "name": "Jerry Terry",
        "phone": "",
        "email": "",
        "office": "RE/MAX Tyler",
        "brokerage": "RE/MAX",
        "address": "4300 Kinsey Dr",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.remax.com/real-estate-agents/jerry-terry-tyler-tx/100014304",
        "source": "remax.com",
        "notes": "Licensed since 1979",
    },
    {
        "name": "Matthew Cornelius",
        "phone": "",
        "email": "",
        "office": "RE/MAX Professionals",
        "brokerage": "RE/MAX",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://www.remax.com/real-estate-agents/matthew-cornelius-tyler-tx/100035611",
        "source": "remax.com",
        "notes": "13+ yrs; 420+ properties sold; serves Smith County / Lake Tyler",
    },
    {
        "name": "Skylar Davis",
        "phone": "",
        "email": "",
        "office": "RE/MAX Professionals",
        "brokerage": "RE/MAX",
        "address": "1698 West Grande Blvd",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.remax.com/real-estate-agents/skylar-davis-tyler-tx/101411037",
        "source": "remax.com",
        "notes": "",
    },
    {
        "name": "Katie Struhall",
        "phone": "(903) 721-5608",
        "email": "katie@struhall.com",
        "office": "RE/MAX Tyler",
        "brokerage": "RE/MAX",
        "address": "4300 Kinsey Dr",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.har.com/re_max-tyler/broker_GTARTX-95",
        "source": "GTAR search",
        "notes": "",
    },
    # Burks Team — RE/MAX
    {
        "name": "Victoria Bauer",
        "phone": "(903) 515-1231",
        "email": "",
        "office": "RE/MAX Tyler — The Burks Team",
        "brokerage": "RE/MAX",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://www.tylerhousehunters.com/about/",
        "source": "tylerhousehunters.com",
        "notes": "",
    },
    {
        "name": "Aaron Burks",
        "phone": "(903) 253-0389",
        "email": "",
        "office": "RE/MAX Tyler — The Burks Team",
        "brokerage": "RE/MAX",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://www.tylerhousehunters.com/about/",
        "source": "tylerhousehunters.com",
        "notes": "",
    },
    {
        "name": "Ben Burks",
        "phone": "(903) 520-0160",
        "email": "",
        "office": "RE/MAX Tyler — The Burks Team",
        "brokerage": "RE/MAX",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://www.tylerhousehunters.com/about/",
        "source": "tylerhousehunters.com",
        "notes": "TX License #520125",
    },
    {
        "name": "Michaela Burks",
        "phone": "(903) 830-4278",
        "email": "",
        "office": "RE/MAX Tyler — The Burks Team",
        "brokerage": "RE/MAX",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://www.tylerhousehunters.com/about/",
        "source": "tylerhousehunters.com",
        "notes": "",
    },

    # ── Keller Williams Realty — Tyler ────────────────────────────────────────
    {
        "name": "KW Tyler Office",
        "phone": "(903) 534-6600",
        "email": "jsattler@kw.com",
        "office": "Keller Williams Realty — Tyler",
        "brokerage": "Keller Williams",
        "address": "6761 Old Jacksonville Hwy",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://tylertx.kw.com/",
        "source": "GTAR search / kw.com",
        "notes": "54 agents on GTAR roster; 23 on NTREIS roster",
    },
    {
        "name": "Claudia Carroll",
        "phone": "",
        "email": "",
        "office": "Keller Williams Realty — Tyler",
        "brokerage": "Keller Williams",
        "address": "6761 Old Jacksonville Hwy",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.tylerhomes.com/",
        "source": "kw.com / tylerhomes.com",
        "notes": "Team leader at TylerHomes.com",
    },

    # ── Ebby Halliday — Tyler ─────────────────────────────────────────────────
    {
        "name": "Ebby Halliday Tyler Office",
        "phone": "(903) 520-2513",
        "email": "terrieking@ebby.com",
        "office": "Ebby Halliday, REALTORS®",
        "brokerage": "Ebby Halliday",
        "address": "2104 W. Grande Blvd, Suite 100",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.ebby.com/roster/offices/tyler/2",
        "source": "ebby.com",
        "notes": "30+ agents; founded as Cornerstone Brokerage 1997",
    },
    {
        "name": "Shelley Calhoun",
        "phone": "(903) 714-4826",
        "email": "shelleycalhoun@ebby.com",
        "office": "Ebby Halliday, REALTORS®",
        "brokerage": "Ebby Halliday",
        "address": "2104 W. Grande Blvd, Suite 100",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.har.com/ebby-halliday-realtors---tyler/office_agents_gtartx-129",
        "source": "GTAR search / har.com",
        "notes": "",
    },
    {
        "name": "Michael Smith",
        "phone": "(903) 316-6928",
        "email": "",
        "office": "Ebby Halliday, REALTORS®",
        "brokerage": "Ebby Halliday",
        "address": "2104 W. Grande Blvd, Suite 100",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.har.com/ebby-halliday-realtors---tyler/office_agents_gtartx-129",
        "source": "har.com",
        "notes": "",
    },
    {
        "name": "Anna Tanksley",
        "phone": "(903) 520-8838",
        "email": "",
        "office": "Ebby Halliday, REALTORS®",
        "brokerage": "Ebby Halliday",
        "address": "2104 W. Grande Blvd, Suite 100",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.har.com/ebby-halliday-realtors---tyler/office_agents_gtartx-129",
        "source": "har.com",
        "notes": "",
    },
    {
        "name": "Rochelle Kasue",
        "phone": "(903) 714-9918",
        "email": "",
        "office": "Ebby Halliday, REALTORS®",
        "brokerage": "Ebby Halliday",
        "address": "2104 W. Grande Blvd, Suite 100",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.har.com/ebby-halliday-realtors---tyler/office_agents_gtartx-129",
        "source": "har.com",
        "notes": "",
    },

    # ── eXp Realty — Tyler ────────────────────────────────────────────────────
    {
        "name": "The Property Shoppe Group (eXp Realty)",
        "phone": "(903) 561-2200",
        "email": "Kim.Houser@eXpRealty.com",
        "office": "The Property Shoppe — eXp Realty",
        "brokerage": "eXp Realty",
        "address": "5230 Old Jacksonville Hwy, Ste 205",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "https://www.thepropertyshoppetyler.com/agents.php",
        "source": "GTAR search / thepropertyshoppetyler.com",
        "notes": "Team; notable agents: Joni Rudak, Jason Mears",
    },
    {
        "name": "Tracey Blanks",
        "phone": "",
        "email": "",
        "office": "eXp Realty",
        "brokerage": "eXp Realty",
        "address": "112 E. Line Street #204",
        "city": "Tyler", "state": "TX", "zip": "75702",
        "profile_url": "https://traceyblanks.exprealty.com/",
        "source": "exprealty.com",
        "notes": "Serves Smith, Wood, Rusk, Cherokee, Henderson, Upshur, Gregg counties",
    },
    {
        "name": "Lacy Walker",
        "phone": "",
        "email": "",
        "office": "eXp Realty",
        "brokerage": "eXp Realty",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://lacywalker.exprealty.com/",
        "source": "exprealty.com",
        "notes": "Specializes greater Tyler area and Smith County",
    },
    {
        "name": "Ginger Brawner",
        "phone": "",
        "email": "",
        "office": "Legacy Real Estate Group — eXp Realty",
        "brokerage": "eXp Realty",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://gingerbrawner.exprealty.com/",
        "source": "exprealty.com",
        "notes": "",
    },

    # ── RealEdge Real Estate ──────────────────────────────────────────────────
    {
        "name": "RealEdge Real Estate Office",
        "phone": "(903) 561-0000",
        "email": "",
        "office": "RealEdge Real Estate",
        "brokerage": "RealEdge (Independent)",
        "address": "3302 Old Jacksonville Rd",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://realedgetyler.com/",
        "source": "yelp / har.com",
        "notes": "Locally-owned independent brokerage",
    },
    {
        "name": "Phyllis Roberts",
        "phone": "(903) 539-2279",
        "email": "phyllismroberts69@gmail.com",
        "office": "RealEdge Real Estate",
        "brokerage": "RealEdge (Independent)",
        "address": "3302 Old Jacksonville Rd",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/realedge-real-estate/broker_REDT01",
        "source": "GTAR search",
        "notes": "",
    },
    {
        "name": "Phillip Lloyd",
        "phone": "(903) 561-0000",
        "email": "phillip@tylerrealedge.com",
        "office": "RealEdge Real Estate",
        "brokerage": "RealEdge (Independent)",
        "address": "3302 Old Jacksonville Rd",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.zoominfo.com/p/Phillip-Lloyd/8483905398",
        "source": "ZoomInfo / search",
        "notes": "",
    },
    {
        "name": "Doc Deason",
        "phone": "(903) 561-0000",
        "email": "",
        "office": "RealEdge Real Estate",
        "brokerage": "RealEdge (Independent)",
        "address": "3302 Old Jacksonville Rd",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://realedgetyler.com/",
        "source": "Yelp reviews",
        "notes": "",
    },
    {
        "name": "Robin Fields",
        "phone": "(903) 561-0000",
        "email": "",
        "office": "RealEdge Real Estate",
        "brokerage": "RealEdge (Independent)",
        "address": "3302 Old Jacksonville Rd",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://www.har.com/realedge-real-estate/broker_REDT01",
        "source": "har.com",
        "notes": "",
    },
    {
        "name": "Don Bates",
        "phone": "(903) 561-0000",
        "email": "",
        "office": "RealEdge Real Estate",
        "brokerage": "RealEdge (Independent)",
        "address": "3302 Old Jacksonville Rd",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://realedgetyler.com/",
        "source": "ZoomInfo / search",
        "notes": "",
    },
    {
        "name": "Stephanie Warren",
        "phone": "(903) 561-0000",
        "email": "",
        "office": "RealEdge Real Estate",
        "brokerage": "RealEdge (Independent)",
        "address": "3302 Old Jacksonville Rd",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://realedgetyler.com/",
        "source": "ZoomInfo / search",
        "notes": "",
    },
    {
        "name": "Tina Adams",
        "phone": "(903) 561-0000",
        "email": "",
        "office": "RealEdge Real Estate",
        "brokerage": "RealEdge (Independent)",
        "address": "3302 Old Jacksonville Rd",
        "city": "Tyler", "state": "TX", "zip": "75701",
        "profile_url": "https://realedgetyler.com/",
        "source": "ZoomInfo / search",
        "notes": "",
    },

    # ── Gregory Realtors ──────────────────────────────────────────────────────
    {
        "name": "Cindy Gregory",
        "phone": "",
        "email": "",
        "office": "Gregory Realtors",
        "brokerage": "Gregory Real Estate",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://gregoryrealtors.com/about/meet-our-agents/",
        "source": "gregoryrealtors.com",
        "notes": "Broker; 30+ years East Texas experience",
    },
    {
        "name": "Jason Gregory",
        "phone": "",
        "email": "",
        "office": "Gregory Realtors",
        "brokerage": "Gregory Real Estate",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://gregoryrealtors.com/about/meet-our-agents/",
        "source": "gregoryrealtors.com",
        "notes": "Associate Broker",
    },
    {
        "name": "Emily Smith",
        "phone": "",
        "email": "",
        "office": "Gregory Realtors",
        "brokerage": "Gregory Real Estate",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://gregoryrealtors.com/about/meet-our-agents/",
        "source": "gregoryrealtors.com",
        "notes": "Realtor",
    },
    {
        "name": "Sam Zigtema",
        "phone": "",
        "email": "",
        "office": "Gregory Realtors",
        "brokerage": "Gregory Real Estate",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://gregoryrealtors.com/about/meet-our-agents/",
        "source": "gregoryrealtors.com",
        "notes": "Realtor",
    },
    {
        "name": "Mike Mathews",
        "phone": "",
        "email": "",
        "office": "Gregory Realtors",
        "brokerage": "Gregory Real Estate",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://gregoryrealtors.com/about/meet-our-agents/",
        "source": "gregoryrealtors.com",
        "notes": "Realtor",
    },
    {
        "name": "Nichol Wildt",
        "phone": "",
        "email": "",
        "office": "Gregory Realtors",
        "brokerage": "Gregory Real Estate",
        "address": "",
        "city": "Tyler", "state": "TX", "zip": "",
        "profile_url": "https://gregoryrealtors.com/about/meet-our-agents/",
        "source": "gregoryrealtors.com",
        "notes": "Realtor",
    },

    # ── Other brokerages / misc ───────────────────────────────────────────────
    {
        "name": "Realty One Group Rose Office",
        "phone": "(903) 520-6895",
        "email": "doughays03@gmail.com",
        "office": "Realty One Group Rose",
        "brokerage": "Realty One Group",
        "address": "1042 Asher Way, Ste 200",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "",
        "source": "GTAR search",
        "notes": "",
    },
    {
        "name": "Alysha Woodfin",
        "phone": "(903) 752-8985",
        "email": "alysha.woodfin.realtor@gmail.com",
        "office": "East Texas Homes & Land LLC",
        "brokerage": "East Texas Homes & Land",
        "address": "24289 Hwy 64 E",
        "city": "Troup", "state": "TX", "zip": "75789",
        "profile_url": "",
        "source": "GTAR search",
        "notes": "Smith County adjacent — Troup TX",
    },
    {
        "name": "Laura Curbow",
        "phone": "(903) 262-8633",
        "email": "lauracurbow903@gmail.com",
        "office": "Dwell Realty",
        "brokerage": "Dwell Realty",
        "address": "7248 Crosswater",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "",
        "source": "GTAR search",
        "notes": "",
    },
    {
        "name": "Joyce Shilling",
        "phone": "(903) 521-9058",
        "email": "joyce@shillingrealestate.com",
        "office": "Shilling Real Estate Company",
        "brokerage": "Shilling Real Estate",
        "address": "102 S. College",
        "city": "Tyler", "state": "TX", "zip": "75702",
        "profile_url": "",
        "source": "GTAR search",
        "notes": "",
    },
    {
        "name": "Kim Cooley",
        "phone": "(903) 571-2410",
        "email": "kimcooley@kimcooley.net",
        "office": "Riot Cow Properties LLC",
        "brokerage": "Riot Cow Properties",
        "address": "P.O. Box 6073",
        "city": "Tyler", "state": "TX", "zip": "75711",
        "profile_url": "",
        "source": "GTAR search",
        "notes": "",
    },
    {
        "name": "Kim Houser",
        "phone": "(903) 330-2919",
        "email": "Kim.Houser@eXpRealty.com",
        "office": "The Property Shoppe — eXp Realty",
        "brokerage": "eXp Realty",
        "address": "5230 Old Jacksonville Hwy Ste 205",
        "city": "Tyler", "state": "TX", "zip": "75703",
        "profile_url": "",
        "source": "GTAR search",
        "notes": "",
    },
]

os.makedirs("output", exist_ok=True)
with open(OUTPUT, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDS)
    writer.writeheader()
    for row in contacts:
        # fill any missing keys with ""
        writer.writerow({k: row.get(k, "") for k in FIELDS})

print(f"Done — {len(contacts)} records written to {OUTPUT}")
