#!/usr/bin/env python3
"""Generate SKILLS.md at the repo root from skill frontmatter.

Run after any skill change:

    python3 scripts/generate_skills_registry.py

CI mode (fails if SKILLS.md is stale rather than rewriting it):

    python3 scripts/generate_skills_registry.py --check
"""

from __future__ import annotations

import sys

from skill_metadata import (
    REPO_ROOT,
    Skill,
    collect_skills,
    load_registered,
)

OUTPUT = REPO_ROOT / "SKILLS.md"


def short_desc(text: str, max_len: int = 150) -> str:
    if not text:
        return "—"
    first = text.split(". ", 1)[0].rstrip(".")
    if len(first) > max_len:
        first = first[: max_len - 1].rstrip() + "…"
    return first


def render(skills: list[Skill], registered: list[str]) -> str:
    lines: list[str] = []
    lines.append("# ETKM Skills Registry")
    lines.append("")
    lines.append(
        "> Auto-generated by `scripts/generate_skills_registry.py`. Do not "
        "edit by hand — regenerate after any skill change. CI verifies this "
        "file is current on every push."
    )
    lines.append("")

    lines.append("## Layout Doctrine")
    lines.append("")
    lines.append(
        "- `skills/user/` — canonical home for every ETKM-specific skill. "
        "Anthropic mounts a subset at `/mnt/skills/user/` in Claude.ai chat "
        "sessions; the mounted list lives in `skills/user/REGISTERED.txt`."
    )
    lines.append("- `skills/` — general-purpose, non-ETKM skills only.")
    lines.append("- `archive/` — retired skills, left in place for reference. Never modified.")
    lines.append("")

    lines.append("## Active Skills")
    lines.append("")
    lines.append("| Skill | Location | Version | Updated | Purpose |")
    lines.append("|---|---|---|---|---|")
    for s in skills:
        lines.append(
            f"| `{s.name}` | `{s.location}` | {s.version} | {s.updated} | "
            f"{short_desc(s.description)} |"
        )
    lines.append("")

    lines.append("## Disk Mount Registration")
    lines.append("")
    lines.append(
        "These skills are uploaded to Claude.ai (Customize → Skills) and load "
        "automatically in chat sessions from `/mnt/skills/user/`. Skills are "
        "private to each account and uploaded individually. We mirror the "
        "uploaded list in `skills/user/REGISTERED.txt` so CI can detect drift "
        "between repo and mount. Upload procedure: `docs/skill-upload-procedure.md`."
    )
    lines.append("")
    lines.append("| Skill | In Repo? | Notes |")
    lines.append("|---|---|---|")

    repo_user = {s.name for s in skills if s.location.startswith("skills/user/")}
    for name in sorted(registered):
        in_repo = name in repo_user
        check = "yes" if in_repo else "**no**"
        note = "—" if in_repo else "**Missing from repo.** Either author it or remove from REGISTERED.txt."
        lines.append(f"| `{name}` | {check} | {note} |")
    lines.append("")

    pending = sorted(
        s.name
        for s in skills
        if s.location.startswith("skills/user/") and s.name not in set(registered)
    )
    lines.append("### Pending Upload")
    lines.append("")
    if pending:
        lines.append(
            "In repo at `skills/user/` but not yet uploaded to Claude.ai. To "
            "onboard them, run `python3 scripts/package_skills.py --pending` "
            "to produce ZIPs in `dist/skills/`, then upload each via "
            "Claude.ai → Customize → Skills. Mirror the upload back to "
            "`REGISTERED.txt` afterward. Full procedure: "
            "`docs/skill-upload-procedure.md`."
        )
        lines.append("")
        for name in pending:
            lines.append(f"- `{name}`")
    else:
        lines.append("None — every skill in `skills/user/` is uploaded to Claude.ai.")
    lines.append("")

    lines.append("## Schema")
    lines.append("")
    lines.append("Every `SKILL.md` must contain YAML frontmatter with:")
    lines.append("")
    lines.append("- `name` — slug matching the directory name")
    lines.append("- `version` — semver-style (e.g. `1.0`, `2.3`)")
    lines.append("- `updated` — ISO date (`YYYY-MM-DD`)")
    lines.append("- `description` — when to load the skill, scope, exclusions")
    lines.append("")
    lines.append(
        "`.github/workflows/validate-skills.yml` enforces this schema and "
        "the SKILLS.md freshness check on every push."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    skills = collect_skills()
    registered = load_registered()
    new_content = render(skills, registered)

    if "--check" in sys.argv:
        if not OUTPUT.exists():
            print("SKILLS.md is missing — run scripts/generate_skills_registry.py and commit.", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != new_content:
            print(
                "SKILLS.md is stale — run scripts/generate_skills_registry.py "
                "and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"SKILLS.md is current ({len(skills)} skills).")
        return 0

    OUTPUT.write_text(new_content, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(skills)} skills).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
